import foto1 from "../Images/oneDayHike/1.jpg";
import foto2 from "../Images/oneDayHike/2.jpg";
import foto3 from "../Images/oneDayHike/3.jpg";
import foto4 from "../Images/oneDayHike/4.jpg";
import foto5 from "../Images/oneDayHike/5.jpg";
import foto6 from "../Images/oneDayHike/6.jpg";
import foto7 from "../Images/oneDayHike/7.jpg";
import foto8 from "../Images/oneDayHike/8.jpg";
import foto9 from "../Images/oneDayHike/9.jpg";
import foto10 from "../Images/oneDayHike/10.jpg";
import foto11 from "../Images/oneDayHike/11.jpg";
import foto12 from "../Images/oneDayHike/12.jpg";
import foto13 from "../Images/oneDayHike/13.jpg";
import foto14 from "../Images/oneDayHike/14.jpg";
import foto15 from "../Images/oneDayHike/15.jpg";
import foto16 from "../Images/oneDayHike/16.jpg";
import foto17 from "../Images/oneDayHike/17.jpg";
import foto18 from "../Images/oneDayHike/18.jpg";

export const hikeOneDayArray = [
    {
        id: 1,
        category: "one day hike",
        hikeLength: 4,
        dificult: "Сложность низкая",
        name: "Водопад Джур-Джур и Хапхальское ущелье",
        cost: 4000,
        image: foto1,
    },
    {
        id: 2,
        category: "one day hike",
        hikeLength: 6,
        dificult: "Сложность средняя",
        name: "Гора Ильяс-Кая и храм Солнца",
        cost: 4000,
        image: foto2,
    },
    {
        id: 3,
        category: "one day hike",
        hikeLength: 8,
        dificult: "Сложность средняя",
        name: "Красная пещера и гора Янкой-Баир",
        cost: 4000,
        image: foto3,
    },
    {
        id: 4,
        category: "one day hike",
        hikeLength: 6,
        dificult: "Сложность высокая",
        name: "Через перевал к морю - пляж Инжир",
        cost: 4000,
        image: foto4,
    },
    {
        id: 5,
        category: "one day hike",
        hikeLength: 4,
        dificult: "Сложность низкая",
        name: "Большой каньон Крыма",
        cost: 4000,
        image: foto5,
    },
    {
        id: 6,
        category: "one day hike",
        hikeLength: 6,
        dificult: "Сложность высокая",
        name: "Гора Роман-Кош",
        cost: 4000,
        image: foto6,
    },
    {
        id: 7,
        category: "one day hike",
        hikeLength: 18,
        dificult: "Сложность средняя",
        name: "Гора Южная Демерджи и Долина привидений",
        cost: 4000,
        image: foto7,
    },
    {
        id: 8,
        category: "one day hike",
        hikeLength: 7,
        dificult: "Сложность средняя",
        name: "Бирюзовое озеро и гора Чатан-Байры",
        cost: 4000,
        image: foto8,
    },
    {
        id: 9,
        category: "one day hike",
        hikeLength: 4,
        dificult: "Сложность низкая",
        name: "Пещерный город Чуфут-Кале",
        cost: 4000,
        image: foto9
    },
    {
        id: 10,
        category: "one day hike",
        hikeLength: 7,
        dificult: "Сложность средняя",
        name: "Водопады Козырек и Рыжий Кубалар",
        cost: 4000,
        image: foto10,
    },
    {
        id: 11,
        category: "one day hike",
        hikeLength: 13,
        dificult: "Сложность высокая",
        name: "Пещера Бинбаш-Коба",
        cost: 4000,
        image: foto11,
    },
    {
        id: 12,
        category: "one day hike",
        hikeLength: 14,
        dificult: "Сложность высокая",
        name: "От Балаклавы до Ласпи",
        cost: 4000,
        image: foto12,
    },
    {
        id: 13,
        category: "one day hike",
        hikeLength: 6,
        dificult: "Сложность средняя",
        name: "Боткинская тропа и водопад Учан-СУ",
        cost: 4000,
        image: foto13,
    },
    {
        id: 14,
        category: "one day hike",
        hikeLength: 12,
        dificult: "Сложность средняя",
        name: "Чернореченский каньон",
        cost: 4000,
        image: foto14,
    },
    {
        id: 15,
        category: "one day hike",
        hikeLength: 9,
        dificult: "Сложность средняя",
        name: "Тропа Голицина и Царский пляж",
        cost: 4000,
        image: foto15,
    },
    {
        id: 16,
        category: "one day hike",
        hikeLength: 9,
        dificult: "Сложность высокая",
        name: "Гора Ай-Петри",
        cost: 4000,
        image: foto16,
    },

    {
        id: 17,
        category: "one day hike",
        hikeLength: 9,
        dificult: "Сложность средняя",
        name: "Гора Эклизи-Бурун - верхнее плато Чатыр-Дага",
        cost: 4000,
        image: foto17,
    },
    {
        id: 18,
        category: "one day hike",
        hikeLength: 7,
        dificult: "Сложность средняя",
        name: "Шаан-Кая и Малая Шаан-Кая",
        cost: 4000,
        image: foto18,
    },
];

export const questArray = [
    {
        id: 1,
        category: "quest",
        hikeLength: 5,
        dificult: "Сложность веселящая",
        name: "Активный квест",
        cost: 3000,
        image: "https://vsegda-pomnim.com/uploads/posts/2022-04/1649119091_20-vsegda-pomnim-com-p-zagadki-prirodi-foto-22.jpg",
    },
    {
        id: 2,
        name: "Долина с рекой",
        hikeLength: 1,
        dificult: "Пассивынй квест",
        cost: 4000,
        category: "one day hike",
        image: "https://vsegda-pomnim.com/uploads/posts/2022-04/1649119126_22-vsegda-pomnim-com-p-zagadki-prirodi-foto-24.jpg",
    },
    {
        id: 3,
        category: "one day hike",
        name: "Квестик",
        hikeLength: 340,
        dificult: "Сложность тяжёлая",
        cost: 4000,
        image: "https://mebellka.ru/wp-content/uploads/c/d/d/cddf2feb3685b902ec543e87102130a3.jpeg",
    },
    {
        id: 4,
        category: "one day hike",
        hikeLength: 11,
        name: "Суровые квесты",
        dificult: "Сложность низкая",
        cost: 4000,
        image: "https://vsegda-pomnim.com/uploads/posts/2022-04/1649119111_15-vsegda-pomnim-com-p-zagadki-prirodi-foto-15.jpg",
    },
    {
        id: 5,
        category: "one day hike",
        hikeLength: 13,
        name: "Лес с квестами",
        dificult: "Сложность средняя",
        cost: 4000,
        image: "http://uduba.com/user_data/e9/fb/e9fbfdf94352f9a0623f081466b2e3b3.jpg",
    },
    {
        id: 6,
        category: "one day hike",
        hikeLength: 33,
        name: "Идём по квесту",
        dificult: "Сложность супертяж",
        cost: 9000,
        image: "https://funart.pro/uploads/posts/2022-08/1660910159_3-funart-pro-p-zagadki-prirodi-krasivo-4.jpg",
    },
];

export const excursionsArray = [
    {
        id: 1,
        category: "excursions",
        hikeLength: 5,
        dificult: "Сложность веселящая",
        name: "Активный квест",
        cost: 3000,
        image: "https://fikiwiki.com/uploads/posts/2022-02/1645055506_50-fikiwiki-com-p-shutochnie-kartinki-53.jpg",
    },
    {
        id: 2,
        name: "Долина с рекой",
        hikeLength: 1,
        dificult: "'rcre",
        cost: 4000,
        category: "excursions",
        image: "",
    },
    {
        id: 3,
        category: "excursions",
        name: "Квестик",
        hikeLength: 34,
        dificult: "Сложность тяжёлая",
        cost: 4000,
        image: "",
    },
    {
        id: 4,
        category: "excursions",
        hikeLength: 1,
        name: "Суровые квесты",
        dificult: "Сложность низкая",
        cost: 4000,
        image: "",
    },
    {
        id: 5,
        category: "excursions",
        hikeLength: 3,
        name: "Лес с квестами",
        dificult: "Сложность средняя",
        cost: 4000,
        image: "",
    },
    {
        id: 6,
        category: "excursions",
        hikeLength: 3,
        name: "Идём по квесту",
        dificult: "Сложность супертяж",
        cost: 9000,
        image: "",
    },
];

export const climbingArray = [
    {
        id: 1,
        category: "climbing",
        hikeLength: 5,
        dificult: "трудно",
        name: "Лазание вертикльное",
        cost: 3000,
        image: "https://dasart.ru/userdata/image/ce/34/ce3439fc22e67020c2ee4f1b7a9e3fd2.jpg",
    },
    {
        id: 2,
        category: "climbing",
        name: "Лазание горизонтальное",
        hikeLength: 1,
        dificult: "Легко",
        cost: 4000,

        image: "https://h-i.su/wp-content/uploads/2015/10/water_climbing_1-1.jpg",
    },
    {
        id: 3,
        category: "climbing",
        name: "Лазание с пучком",
        hikeLength: 34,
        dificult: "Сложность тяжёлая",
        cost: 4000,
        image: "https://www.tk-turin.ru/upload/iblock/a68/a686716afc47ca13f9babbce10b0b080.jpg",
    },
    {
        id: 4,
        category: "climbing",
        hikeLength: 1,
        name: "Перелазание",
        dificult: "Сложность низкая",
        cost: 4000,
        image: "https://inngreece.ru/assets/images/news/kalimnos-ostrov-skalolazov.jpg",
    },
    {
        id: 5,
        category: "climbing",
        hikeLength: 3,
        name: "Пролаз кучкой",
        dificult: "Сложность средняя",
        cost: 4000,
        image: "https://gotonature.ru/uploads/posts/2019-11/1574159576_alpinizm-i-skalolazanie1.jpg",
    },
    {
        id: 6,
        category: "climbing",
        hikeLength: 3,
        name: "Вылазивание",
        dificult: "Сложность супертяж",
        cost: 9000,
        image: "https://sun9-51.userapi.com/impg/uqVV8codlDTx3TlbHqGHJecDdZHKlzmyew36Ng/dBh6Ya9boC8.jpg?size=604x453&quality=96&sign=512af28e6f73877354497be79b0082cc&type=album",
    },
];
