import foto1 from "../Images/oneDayHike/1.jpg";
import foto2 from "../Images/oneDayHike/2.jpg";
import foto3 from "../Images/oneDayHike/3.jpg";
import foto4 from "../Images/oneDayHike/4.jpg";
import foto5 from "../Images/oneDayHike/5.jpg";
import foto6 from "../Images/oneDayHike/6.jpg";
import foto7 from "../Images/oneDayHike/7.jpg";
import foto8 from "../Images/oneDayHike/8.jpg";
import foto9 from "../Images/oneDayHike/9.jpg";
import foto10 from "../Images/oneDayHike/10.jpg";
import foto11 from "../Images/oneDayHike/11.jpg";
import foto12 from "../Images/oneDayHike/12.jpg";
import foto13 from "../Images/oneDayHike/13.jpg";
import foto14 from "../Images/oneDayHike/14.jpg";
import foto15 from "../Images/oneDayHike/15.jpg";
import foto16 from "../Images/oneDayHike/16.jpg";
import foto17 from "../Images/oneDayHike/17.jpg";
import foto18 from "../Images/oneDayHike/18.jpg";

import { bankFoto } from "./bankFoto";

export const hikeOneDayArray = [
    {
        id: 1,
        hikeLengthTitle: "Длинна маршрута, км: ",
        category: "one day hike",
        hikeLength: 4,
        dificult: "Сложность низкая",
        name: "Водопад Джур-Джур и Хапхальское ущелье",
        cost: 4000,
        image: foto1,
        costTitle: "с группы",
    },
    {
        id: 2,
        hikeLengthTitle: "Длинна маршрута, км: ",
        category: "one day hike",
        hikeLength: 6,
        dificult: "Сложность средняя",
        name: "Гора Ильяс-Кая и храм Солнца",
        cost: 4000,
        image: foto2,
        costTitle: "с группы",
    },
    {
        id: 3,
        hikeLengthTitle: "Длинна маршрута, км: ",
        category: "one day hike",
        hikeLength: 8,
        dificult: "Сложность средняя",
        name: "Красная пещера и гора Янкой-Баир",
        cost: 4000,
        image: foto3,
        costTitle: "с группы",
    },
    {
        id: 4,
        hikeLengthTitle: "Длинна маршрута, км: ",
        category: "one day hike",
        hikeLength: 6,
        dificult: "Сложность высокая",
        name: "Через перевал к морю - пляж Инжир",
        cost: 4000,
        image: foto4,
        costTitle: "с группы",
    },
    {
        id: 5,
        hikeLengthTitle: "Длинна маршрута, км: ",
        category: "one day hike",
        hikeLength: 4,
        dificult: "Сложность низкая",
        name: "Большой каньон Крыма",
        cost: 4000,
        image: foto5,
        costTitle: "с группы",
    },
    {
        id: 6,
        hikeLengthTitle: "Длинна маршрута, км: ",
        category: "one day hike",
        hikeLength: 6,
        dificult: "Сложность высокая",
        name: "Гора Роман-Кош",
        cost: 4000,
        image: foto6,
        costTitle: "с группы",
    },
    {
        id: 7,
        hikeLengthTitle: "Длинна маршрута, км: ",
        category: "one day hike",
        hikeLength: 18,
        dificult: "Сложность средняя",
        name: "Гора Южная Демерджи и Долина привидений",
        cost: 4000,
        image: foto7,
        costTitle: "с группы",
    },
    {
        id: 8,
        hikeLengthTitle: "Длинна маршрута, км: ",
        category: "one day hike",
        hikeLength: 7,
        dificult: "Сложность средняя",
        name: "Бирюзовое озеро и гора Чатан-Байры",
        cost: 4000,
        image: foto8,
        costTitle: "с группы",
    },
    {
        id: 9,
        hikeLengthTitle: "Длинна маршрута, км: ",
        category: "one day hike",
        hikeLength: 4,
        dificult: "Сложность низкая",
        name: "Пещерный город Чуфут-Кале",
        cost: 4000,
        image: foto9,
        costTitle: "с группы",
    },
    {
        id: 10,
        hikeLengthTitle: "Длинна маршрута, км: ",
        category: "one day hike",
        hikeLength: 7,
        dificult: "Сложность средняя",
        name: "Водопады Козырек и Рыжий Кубалар",
        cost: 4000,
        image: foto10,
        costTitle: "с группы",
    },
    {
        id: 11,
        hikeLengthTitle: "Длинна маршрута, км: ",
        category: "one day hike",
        hikeLength: 13,
        dificult: "Сложность высокая",
        name: "Пещера Бинбаш-Коба",
        cost: 4000,
        image: foto11,
        costTitle: "с группы",
    },
    {
        id: 12,
        hikeLengthTitle: "Длинна маршрута, км: ",
        category: "one day hike",
        hikeLength: 14,
        dificult: "Сложность высокая",
        name: "От Балаклавы до Ласпи",
        cost: 4000,
        image: foto12,
        costTitle: "с группы",
    },
    {
        id: 13,
        hikeLengthTitle: "Длинна маршрута, км: ",
        category: "one day hike",
        hikeLength: 6,
        dificult: "Сложность средняя",
        name: "Боткинская тропа и водопад Учан-СУ",
        cost: 4000,
        image: foto13,
        costTitle: "с группы",
    },
    {
        id: 14,
        hikeLengthTitle: "Длинна маршрута, км: ",
        category: "one day hike",
        hikeLength: 12,
        dificult: "Сложность средняя",
        name: "Чернореченский каньон",
        cost: 4000,
        image: foto14,
        costTitle: "с группы",
    },
    {
        id: 15,
        hikeLengthTitle: "Длинна маршрута, км: ",
        category: "one day hike",
        hikeLength: 9,
        dificult: "Сложность средняя",
        name: "Тропа Голицина и Царский пляж",
        cost: 4000,
        image: foto15,
        costTitle: "с группы",
    },
    {
        id: 16,
        hikeLengthTitle: "Длинна маршрута, км: ",
        category: "one day hike",
        hikeLength: 9,
        dificult: "Сложность высокая",
        name: "Гора Ай-Петри",
        cost: 4000,
        image: foto16,
        costTitle: "с группы",
    },

    {
        id: 17,
        hikeLengthTitle: "Длинна маршрута, км: ",
        category: "one day hike",
        hikeLength: 9,
        dificult: "Сложность средняя",
        name: "Гора Эклизи-Бурун - плато Чатыр-Дага",
        cost: 4000,
        image: foto17,
        costTitle: "с группы",
    },
    {
        id: 18,
        hikeLengthTitle: "Длинна маршрута, км: ",
        category: "one day hike",
        hikeLength: 7,
        dificult: "Сложность средняя",
        name: "Шаан-Кая и Малая Шаан-Кая",
        cost: 4000,
        image: foto18,
        costTitle: "с группы",
    },
];

export const questArray = [
    {
        id: 1,
        category: "quest",
        hikeLength: 5,
        dificult: "Сложность веселящая",
        name: "Активный квест",
        cost: 3000,
        image: "https://vsegda-pomnim.com/uploads/posts/2022-04/1649119091_20-vsegda-pomnim-com-p-zagadki-prirodi-foto-22.jpg",
    },
    {
        id: 2,
        name: "Долина с рекой",
        hikeLength: 1,
        dificult: "Пассивынй квест",
        cost: 4000,
        category: "one day hike",
        image: "https://vsegda-pomnim.com/uploads/posts/2022-04/1649119126_22-vsegda-pomnim-com-p-zagadki-prirodi-foto-24.jpg",
    },
    {
        id: 3,
        category: "one day hike",
        name: "Квестик",
        hikeLength: 340,
        dificult: "Сложность тяжёлая",
        cost: 4000,
        image: "https://mebellka.ru/wp-content/uploads/c/d/d/cddf2feb3685b902ec543e87102130a3.jpeg",
    },
    {
        id: 4,
        category: "one day hike",
        hikeLength: 11,
        name: "Суровые квесты",
        dificult: "Сложность низкая",
        cost: 4000,
        image: "https://vsegda-pomnim.com/uploads/posts/2022-04/1649119111_15-vsegda-pomnim-com-p-zagadki-prirodi-foto-15.jpg",
    },
    {
        id: 5,
        category: "one day hike",
        hikeLength: 13,
        name: "Лес с квестами",
        dificult: "Сложность средняя",
        cost: 4000,
        image: "http://uduba.com/user_data/e9/fb/e9fbfdf94352f9a0623f081466b2e3b3.jpg",
    },
    {
        id: 6,
        category: "one day hike",
        hikeLength: 33,
        name: "Идём по квесту",
        dificult: "Сложность супертяж",
        cost: 9000,
        image: "https://funart.pro/uploads/posts/2022-08/1660910159_3-funart-pro-p-zagadki-prirodi-krasivo-4.jpg",
    },
];

export const excursionsArray = [
    {
        id: 1,
        category: "excursions",
        hikeLength: 5,
        dificult: "Сложность веселящая",
        name: "Активный квест",
        cost: 3000,
        image: "https://fikiwiki.com/uploads/posts/2022-02/1645055506_50-fikiwiki-com-p-shutochnie-kartinki-53.jpg",
    },
    {
        id: 2,
        name: "Долина с рекой",
        hikeLength: 1,
        dificult: "'rcre",
        cost: 4000,
        category: "excursions",
        image: "",
    },
    {
        id: 3,
        category: "excursions",
        name: "Квестик",
        hikeLength: 34,
        dificult: "Сложность тяжёлая",
        cost: 4000,
        image: "",
    },
    {
        id: 4,
        category: "excursions",
        hikeLength: 1,
        name: "Суровые квесты",
        dificult: "Сложность низкая",
        cost: 4000,
        image: "",
    },
    {
        id: 5,
        category: "excursions",
        hikeLength: 3,
        name: "Лес с квестами",
        dificult: "Сложность средняя",
        cost: 4000,
        image: "",
    },
    {
        id: 6,
        category: "excursions",
        hikeLength: 3,
        name: "Идём по квесту",
        dificult: "Сложность супертяж",
        cost: 9000,
        image: "",
    },
];

export const climbingArray = [
    {
        id: 1,
        category: "climbing",
        hikeLengthTitle: "Количесвто маршрутов: ",
        hikeLength: "347",
        dificult: "3 - 8b",
        name: "Батилиман",
        cost: 1500,
        costTitle: "с человека",
        image: bankFoto.climbing.foto1,
    },
    {
        id: 2,
        category: "climbing",
        hikeLengthTitle: "Количесвто маршрутов: ",
        hikeLength: "30",
        dificult: "5c - 8b+",
        name: "Комперия",
        cost: 1500,
        costTitle: "с человека",
        image: bankFoto.climbing.foto2,
    },
    {
        id: 3,
        category: "climbing",
        hikeLengthTitle: "Количесвто маршрутов: ",
        hikeLength: "118",
        dificult: "4a - 8b",
        name: "Ильяс-Кая",
        cost: 1500,
        costTitle: "с человека",
        image: bankFoto.climbing.foto3,
    },
    {
        id: 4,
        category: "climbing",
        hikeLengthTitle: "Количесвто маршрутов: ",
        hikeLength: "142",
        dificult: "5b - 9a",
        name: "Сарыч",
        cost: 1500,
        costTitle: "с человека",
        image: bankFoto.climbing.foto4,
    },
    {
        id: 5,
        category: "climbing",
        hikeLengthTitle: "Количесвто маршрутов: ",
        hikeLength: "55",
        dificult: "5a - 7c",
        name: "Парус",
        cost: 1500,
        costTitle: "с человека",
        image: bankFoto.climbing.foto5,
    },
    {
        id: 6,
        category: "climbing",
        hikeLengthTitle: "Количесвто маршрутов: ",
        hikeLength: "20",
        dificult: "5b - 6c",
        name: "Скала 14й километр",
        cost: 1500,
        costTitle: "с человека",
        image: bankFoto.climbing.foto6,
    },
    {
        id: 7,
        category: "climbing",
        hikeLengthTitle: "Количесвто маршрутов: ",
        hikeLength: "94",
        dificult: "5b - 9a",
        name: "Уарч-Кая",
        cost: 1500,
        costTitle: "с человека",
        image: bankFoto.climbing.foto7,
    },
    {
        id: 8,
        category: "climbing",
        hikeLengthTitle: "Количесвто маршрутов: ",
        hikeLength: "232",
        dificult: "4c - 8c",
        name: "Симеиз",
        cost: 1500,
        costTitle: "с человека",
        image: bankFoto.climbing.foto8,
    },
];
