export const hikeOneDayArray = [
    {
        id: 1,
        category: "one day hike",
        hikeLength: 18,
        dificult: "Сложность средняя",
        name: "Снежные горы",
        cost: 4000,
        image: "https://phonoteka.org/uploads/posts/2022-01/1642637697_56-phonoteka-org-p-fon-gori-65.jpg",
    },
    {
        id: 2,
        name: "Долина с рекой",
        hikeLength: 15,
        dificult: "Сложность средняя",
        cost: 4000,
        category: "one day hike",
        image: "https://img1.goodfon.ru/original/800x480/0/cc/nebo-gory-sklon-les-reka.jpg",
    },
    {
        id: 3,
        category: "one day hike",
        name: "Озеро с горами",
        hikeLength: 30,
        dificult: "Сложность тяжёлая",
        cost: 4000,
        image: "https://www.ejin.ru/wp-content/uploads/2019/05/gora-28.jpg",
    },
    {
        id: 4,
        category: "one day hike",
        hikeLength: 11,
        name: "Суровые стены",
        dificult: "Сложность низкая",
        cost: 4000,
        image: "https://vsegda-pomnim.com/uploads/posts/2022-04/1649124761_13-vsegda-pomnim-com-p-priroda-gor-foto-17.jpg",
    },
    {
        id: 5,
        category: "one day hike",
        hikeLength: 13,
        name: "Лес с горами",
        dificult: "Сложность средняя",
        cost: 4000,
        image: "https://mobimg.b-cdn.net/v3/fetch/ec/ec2a1fa64a8faca128077d808e153e1c.jpeg",
    },
    {
        id: 6,
        category: "one day hike",
        hikeLength: 33,
        name: "Идём по гребню",
        dificult: "Сложность супертяж",
        cost: 9000,
        image: "https://sportishka.com/uploads/posts/2022-11/1667475316_52-sportishka-com-p-podnozhya-gori-pinterest-59.jpg",
    },
];

export const questArray = [
    {
        id: 1,
        category: "quest",
        hikeLength: 5,
        dificult: "Сложность веселящая",
        name: "Активный квест",
        cost: 3000,
        image: "https://vsegda-pomnim.com/uploads/posts/2022-04/1649119091_20-vsegda-pomnim-com-p-zagadki-prirodi-foto-22.jpg",
    },
    {
        id: 2,
        name: "Долина с рекой",
        hikeLength: 1,
        dificult: "Пассивынй квест",
        cost: 4000,
        category: "one day hike",
        image: "https://vsegda-pomnim.com/uploads/posts/2022-04/1649119126_22-vsegda-pomnim-com-p-zagadki-prirodi-foto-24.jpg",
    },
    {
        id: 3,
        category: "one day hike",
        name: "Квестик",
        hikeLength: 340,
        dificult: "Сложность тяжёлая",
        cost: 4000,
        image: "https://mebellka.ru/wp-content/uploads/c/d/d/cddf2feb3685b902ec543e87102130a3.jpeg",
    },
    {
        id: 4,
        category: "one day hike",
        hikeLength: 11,
        name: "Суровые квесты",
        dificult: "Сложность низкая",
        cost: 4000,
        image: "https://vsegda-pomnim.com/uploads/posts/2022-04/1649119111_15-vsegda-pomnim-com-p-zagadki-prirodi-foto-15.jpg",
    },
    {
        id: 5,
        category: "one day hike",
        hikeLength: 13,
        name: "Лес с квестами",
        dificult: "Сложность средняя",
        cost: 4000,
        image: "http://uduba.com/user_data/e9/fb/e9fbfdf94352f9a0623f081466b2e3b3.jpg",
    },
    {
        id: 6,
        category: "one day hike",
        hikeLength: 33,
        name: "Идём по квесту",
        dificult: "Сложность супертяж",
        cost: 9000,
        image: "https://funart.pro/uploads/posts/2022-08/1660910159_3-funart-pro-p-zagadki-prirodi-krasivo-4.jpg",
    },
];

export const excursionsArray = [
    {
        id: 1,
        category: "excursions",
        hikeLength: 5,
        dificult: "Сложность веселящая",
        name: "Активный квест",
        cost: 3000,
        image: "https://fikiwiki.com/uploads/posts/2022-02/1645055506_50-fikiwiki-com-p-shutochnie-kartinki-53.jpg",
    },
    {
        id: 2,
        name: "Долина с рекой",
        hikeLength: 1,
        dificult: "'rcre",
        cost: 4000,
        category: "excursions",
        image: "",
    },
    {
        id: 3,
        category: "excursions",
        name: "Квестик",
        hikeLength: 34,
        dificult: "Сложность тяжёлая",
        cost: 4000,
        image: "",
    },
    {
        id: 4,
        category: "excursions",
        hikeLength: 1,
        name: "Суровые квесты",
        dificult: "Сложность низкая",
        cost: 4000,
        image: "",
    },
    {
        id: 5,
        category: "excursions",
        hikeLength: 3,
        name: "Лес с квестами",
        dificult: "Сложность средняя",
        cost: 4000,
        image: "",
    },
    {
        id: 6,
        category: "excursions",
        hikeLength: 3,
        name: "Идём по квесту",
        dificult: "Сложность супертяж",
        cost: 9000,
        image: "",
    },
];

export const climbingArray = [
    {
        id: 1,
        category: "climbing",
        hikeLength: 5,
        dificult: "трудно",
        name: "Лазание вертикльное",
        cost: 3000,
        image: "https://dasart.ru/userdata/image/ce/34/ce3439fc22e67020c2ee4f1b7a9e3fd2.jpg",
    },
    {
        id: 2,
        category: "climbing",
        name: "Лазание горизонтальное",
        hikeLength: 1,
        dificult: "Легко",
        cost: 4000,

        image: "https://h-i.su/wp-content/uploads/2015/10/water_climbing_1-1.jpg",
    },
    {
        id: 3,
        category: "climbing",
        name: "Лазание с пучком",
        hikeLength: 34,
        dificult: "Сложность тяжёлая",
        cost: 4000,
        image: "https://www.tk-turin.ru/upload/iblock/a68/a686716afc47ca13f9babbce10b0b080.jpg",
    },
    {
        id: 4,
        category: "climbing",
        hikeLength: 1,
        name: "Перелазание",
        dificult: "Сложность низкая",
        cost: 4000,
        image: "https://inngreece.ru/assets/images/news/kalimnos-ostrov-skalolazov.jpg",
    },
    {
        id: 5,
        category: "climbing",
        hikeLength: 3,
        name: "Пролаз кучкой",
        dificult: "Сложность средняя",
        cost: 4000,
        image: "https://gotonature.ru/uploads/posts/2019-11/1574159576_alpinizm-i-skalolazanie1.jpg",
    },
    {
        id: 6,
        category: "climbing",
        hikeLength: 3,
        name: "Вылазивание",
        dificult: "Сложность супертяж",
        cost: 9000,
        image: "https://sun9-51.userapi.com/impg/uqVV8codlDTx3TlbHqGHJecDdZHKlzmyew36Ng/dBh6Ya9boC8.jpg?size=604x453&quality=96&sign=512af28e6f73877354497be79b0082cc&type=album",
    },
];
